arch: ResNet50
batch_size: 1
det_gpu_id: 1
det_model_checkpoint: /vtti/scratch/mmdetection/trained_models/shrp2_original_split+extra_data_outside_objects/epoch_10.pth
det_model_classes: /vtti/scratch/mmdetection/classes/classes_shrp2_extra.txt
det_model_config: /vtti/scratch/mmdetection/custom_configs/shrp2+extra/cascade_rcnn_r101_fpn_dconv_c3-c5_1x_coco.py
det_model_threshold: 0.5
dist: 1320
f_pitch: 0
f_yaw: 0
front_pitch: -0.02227941620535548
front_yaw: -0.33525447432179787
gpu: 1
old_front_pitch: 0
old_front_yaw: 0
seg_confidence_threshold: 0.5
seg_config_file: configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml
seg_opts:
- MODEL.WEIGHTS
- detectron2://COCO-PanopticSegmentation/panoptic_fpn_R_101_3x/139514519/model_final_cafdb1.pkl
seg_overlay: 1
snapshot_path: ../driver_gaze_fixation/models/Gaze360/L2CSNet_gaze360.pkl
